### ISSUE TITLE
No '../../data/bathymetry/bathy.mat' file available for greenland_bg_plot.m plot

### ISSUE THREAD

**Issue by shahinmg** [donaldaslater/slater_2022_submelt#1]
Hi Donald,

Thanks for the great repo! I am trying to recreate the greenland_bg_plot.m plot, but I don't believe the bathy.mat file is shared. Maybe I am just not looking in the correct spot. If it is missing, could you share the '../../data/bathymetry/bathy.mat' file in the repo? 

This is on line 30 in the  greenland_bg_plot.m script.

Thank you!

**Comment by donaldaslater** [comment]
Hi Michael,

I think you are right it is missing - I probably didn't upload as it is a few hundred MB. I've sent a direct link to the file to your email - let me know if that works.

Cheers

**Comment by shahinmg** [comment]
Thank you, Donald!
